### ISSUE TITLE
Tiler Error: Unable to open [object Object] HTTP0 attempting to load TileSource

### ISSUE THREAD

**Issue by davidheyman** [imaginerio/omeka-s-docker#10] opened 2020-08-11 10:02 UTC
Now that the files directory is writeable and I've fixed an nginx memory issue, we can successfully upload images. However, I can't get the images to appear in Tiler. Can you check to make sure that Tiler is configured correctly? Also, do you happen to know where the Tiler files are stored? I'll need to make sure that is writeable as well.

**Comment by buccalon** [comment] 2020-08-11 13:54
The folder for images is `files/tile/` and the folder for the tiler script is `/var/www/html/modules/ImageServer`

![Screenshot from 2020-08-11 10-38-47](https://user-images.githubusercontent.com/476699/89904164-f9d55b80-dbbe-11ea-9324-6af9c674fad5.png)

This error is caused by missing the `.dzi` file generated by the tiler (deepzoom)

**Comment by martimpassos** [comment] 2020-08-11 14:54
<img width="691" alt="Screen Shot 2020-08-11 at 11 48 52" src="https://user-images.githubusercontent.com/49573683/89912373-dd3e2100-dbc8-11ea-8d3b-0d0c9313cf99.png">
The tiler appears to be working correctly, looks like a problem with the .dzi file over https. <a href="https://situatedviews.axismaps.io/admin/image/892">This item</a> for instance has been succesfully tiled.

**Comment by davidheyman** [comment] 2020-08-11 15:53
Can you escalate this to Daniel?

**Comment by buccalon** [comment] 2020-08-11 16:45
The sample item is working on Universal Viewer (in the same page):
![Screenshot from 2020-08-11 13-30-55](https://user-images.githubusercontent.com/476699/89923589-3319c580-dbd7-11ea-9d13-b87ac3d56242.png)

But it breaks on Mirador (from the official page):
![Screenshot from 2020-08-11 13-32-14](https://user-images.githubusercontent.com/476699/89923608-37de7980-dbd7-11ea-808d-d5a44ccd77ec.png)

There is an update of OpenSeaDragon to be released in the next version of Omeka-S:
https://github.com/omeka/omeka-s/commit/4f7244de87f428e51a50a494918630bc19bd07b5

Omeka-S forum threads regarding HTTPS:

- https://forum.omeka.org/t/open-ssl-ssh-vs-https/5353
- https://forum.omeka.org/t/omeka-s-and-https/10596

Please @Daniel-KM let us know if you have any inputs.

**Closed as completed** 2020-08-27 10:38 UTC
Labels: bug
